import {
  narrowRegistryRows,
  narrowCanonicalRows,
  narrowRegistryProposals,
  type SynthesisRegistrySelection,
  type SynthesisRegistryReviewState,
  type SynthesisRegistryStrings,
} from "./components/registry/registryTypes";
import type { SynthesisWorkbenchPageSnapshot } from "./synthesisWorkbenchTypes";
import type { SynthesisWorkbenchText } from "./synthesisWorkbenchPanelModel";

export const EMPTY_REGISTRY_REVIEW: SynthesisRegistryReviewState = {
  pendingDecisions: [],
  applying: false,
  applyingProposalIds: [],
  resolvedKeys: [],
};

export function projectRegistrySelection(
  snapshot: SynthesisWorkbenchPageSnapshot,
  pending: string[],
  t: SynthesisWorkbenchText,
  review: SynthesisRegistryReviewState = EMPTY_REGISTRY_REVIEW,
): SynthesisRegistrySelection {
  const registry = snapshot.registry;
  const strings: SynthesisRegistryStrings = {
    referencesSubtitle: t("synthesis-index-references-subtitle"),
    idColumnLabel: "ID",
    expandReferencesLabel: t("synthesis-action-expand"),
    collapseReferencesLabel: t("synthesis-action-collapse"),
    referenceCountTemplate: t("synthesis-index-reference-count"),
    loadingReferencesLabel: t("synthesis-surface-loading-subtitle"),
    artifactDigestTitle: t("synthesis-paper-digest"),
    artifactReferencesTitle: t("synthesis-column-reference"),
    artifactCitationAnalysisTitle: t("synthesis-tab-citation-graph"),
    artifactLiteratureScoreTitle: t("synthesis-column-rating"),
    availableLabel: t("synthesis-index-available"),
    indexEmptyFilteredTitle: t("synthesis-index-no-matches"),
    indexEmptyTitle: t("synthesis-index-empty"),
    indexEmptyFilteredMessage: t("synthesis-index-adjust-filters"),
    indexEmptyMessage: t("synthesis-index-empty-message"),
    referencedEmptyFilteredTitle: t("synthesis-empty-matching-references"),
    referencedEmptyTitle: t("synthesis-empty-matching-references"),
    referencedEmptyFilteredMessage: t(
      "synthesis-canonical-no-references-message",
    ),
    referencedEmptyMessage: t("synthesis-canonical-no-references-message"),
    reviewDrawerTitle: t("synthesis-index-review-title"),
    reviewDrawerZeroOpen: t("synthesis-index-review-zero"),
    reviewDrawerEmptyTitle: t("synthesis-review-empty-index"),
    reviewDrawerEmptyMessageTemplate: t("synthesis-index-review-empty-message"),
    blockedByLabel: t("synthesis-index-blocked-by"),
    proposalIdLabel: t("synthesis-index-proposal-id"),
    indexReviewKindLabel: t("synthesis-index-review-title"),
    cleanupKindLabel: t("synthesis-index-cleanup-kind"),
    zoteroDeletionReviewMeta: t("synthesis-index-deletion-review"),
    zoteroDedupeReviewMeta: t("synthesis-index-dedupe-review"),
    openCleanupMeta: t("synthesis-index-cleanup-review"),
    cleanupBodyFallback: t("synthesis-index-cleanup-body"),
    parentItemFallback: t("synthesis-column-parent-item"),
    unresolvedReferenceFallback: t("synthesis-reference-untitled"),
    unknownTargetLabel: t("synthesis-index-unknown-target"),
    unknownParentItemLabel: t("synthesis-index-unknown-parent"),
    unknownReferenceLabel: t("synthesis-index-unknown-reference"),
    fallbackIdSuffix: "ID",
    proposalKindFallback: t("synthesis-review-proposal-title"),
    mergeSourcesTemplate: t("synthesis-index-merge-sources"),
    pendingMergesTemplate: t("synthesis-index-pending-merges"),
    applyingPendingMergesTemplate: t("synthesis-index-applying-merges"),
    unavailableLabel: t("synthesis-index-unavailable"),
  };
  return {
    activeIndexTool: registry?.filters.activeIndexTool || "none",
    filters: {
      search: registry?.filters.search || "",
      scope: registry?.filters.scope || "library",
      artifactCoverage: registry?.filters.artifactCoverage || "all",
      bindingStatus: registry?.filters.bindingStatus || "all",
      canonicalSearch: registry?.filters.canonicalSearch || "",
      canonicalBinding: registry?.filters.canonicalBinding || "all",
      canonicalGraph: registry?.filters.canonicalGraph || "all",
      canonicalDuplicates: registry?.filters.canonicalDuplicates || "all",
      selectedCanonicalRowId: registry?.filters.selectedCanonicalRowId || "",
      reviewDrawerOpen: registry?.filters.reviewDrawerOpen === true,
      reviewDrawerIndex: registry?.filters.reviewDrawerIndex || 0,
    },
    rows: narrowRegistryRows(registry?.rows),
    visibleRows: narrowRegistryRows(registry?.visibleRows),
    matchProposals: narrowRegistryProposals(registry?.matchProposals),
    cleanupProposals: narrowRegistryProposals(registry?.cleanupProposals),
    canonicalRows: narrowCanonicalRows(registry?.canonicalRows),
    visibleCanonicalRows: narrowCanonicalRows(registry?.visibleCanonicalRows),
    cacheStatus: registry?.cacheStatus.status || "missing",
    pendingOperationKeys: pending,
    lastCompletedOperationKey: snapshot.actions?.lastCompleted?.key || "",
    lastFailedOperationKey: snapshot.actions?.lastFailed?.key || "",
    review,
    strings,
  };
}
