/**
 * Label key set and page bridge for the Built-in Agent settings window.
 *
 * The window's visible copy has two names and this module is the only place
 * that joins them:
 *
 * - FTL message ids in `addon/locale/<locale>/addon.ftl`, the single source of
 *   every translated string.
 * - the short camelCase keys the page passes to `text(labels, key, fallback)`
 *   in `src/dashboard/components/ZoteroAgentSettingsControls.tsx`, collected in
 *   `ZOTERO_AGENT_SETTINGS_PAGE_LABEL_ALIASES`.
 *
 * The host projects the active locale through `buildZoteroAgentSettingsLabels()`
 * into the snapshot `labels` record, so a page key resolves without the page
 * knowing an FTL id. Neither side may invent a name of its own: a new visible
 * string means a new FTL key, an entry in the alias table, and a value for it in
 * every locale. An alias that is missing simply stays absent from the record,
 * which makes the page show its own English fallback rather than a wrong string.
 *
 * This module sits with the settings host because that window and the Pi
 * settings graph it composes stay behind the lazy Pi edge; the dashboard page
 * bundle must not import it.
 */

import { getStringOrFallback } from "../../../utils/locale";
import type { FluentMessageId } from "../../../../typings/i10n";

export const ZOTERO_AGENT_SETTINGS_LABEL_KEYS = [
  "zotero-agent-settings-models-set-general",
  "zotero-agent-settings-models-set-conversation",
  "zotero-agent-settings-models-set-skill-run",
  "zotero-agent-settings-models-set-title",
  // Window and navigation
  "backend-manager-pi-title",
  "zotero-agent-settings-window-title",
  "zotero-agent-settings-window-subtitle",
  "zotero-agent-settings-window-closed",
  "zotero-agent-settings-nav-label",
  "zotero-agent-settings-nav-section-models",
  "zotero-agent-settings-nav-section-extensions",
  "zotero-agent-settings-nav-section-advanced",
  "zotero-agent-settings-nav-onboarding",
  "zotero-agent-settings-nav-models",
  "zotero-agent-settings-nav-mcp",
  "zotero-agent-settings-nav-search",
  "zotero-agent-settings-nav-maintenance",
  "zotero-agent-settings-preferences-hint",
  // Shared actions and drafts
  "zotero-agent-settings-action-save",
  "zotero-agent-settings-action-save-changes",
  "zotero-agent-settings-action-save-and-close",
  "zotero-agent-settings-action-save-and-return",
  "zotero-agent-settings-action-save-and-continue",
  "zotero-agent-settings-action-cancel",
  "zotero-agent-settings-action-continue-editing",
  "zotero-agent-settings-action-discard",
  "zotero-agent-settings-action-remove",
  "zotero-agent-settings-action-confirm",
  "zotero-agent-settings-action-close",
  "zotero-agent-settings-action-add",
  "zotero-agent-settings-action-edit",
  "zotero-agent-settings-action-retry",
  "zotero-agent-settings-action-back",
  "zotero-agent-settings-action-done",
  "zotero-agent-settings-status-saving",
  "zotero-agent-settings-status-save-failed",
  "zotero-agent-settings-status-saved",
  "zotero-agent-settings-unsaved-title",
  "zotero-agent-settings-unsaved-body",
  "zotero-agent-settings-unsaved-connection",
  "zotero-agent-settings-select-placeholder",
  "zotero-agent-settings-field-name",
  "zotero-agent-settings-field-value",
  "zotero-agent-settings-field-value-required",
  "zotero-agent-settings-field-keep-saved",
  "zotero-agent-settings-entry-remove",
  "zotero-agent-settings-empty-entries",
  "zotero-agent-settings-operation-failed",
  "zotero-agent-settings-label-unset",
  // Onboarding
  "zotero-agent-settings-onboarding-title",
  "zotero-agent-settings-onboarding-subtitle",
  "zotero-agent-settings-onboarding-ready",
  "zotero-agent-settings-onboarding-pending",
  "zotero-agent-settings-onboarding-step-start",
  "zotero-agent-settings-onboarding-step-connect",
  "zotero-agent-settings-onboarding-step-model",
  "zotero-agent-settings-onboarding-step-use",
  "zotero-agent-settings-onboarding-choose-service",
  "zotero-agent-settings-onboarding-choose-model",
  "zotero-agent-settings-onboarding-adjust-later",
  "zotero-agent-settings-onboarding-option-chatgpt",
  "zotero-agent-settings-onboarding-option-chatgpt-help",
  "zotero-agent-settings-onboarding-option-api-key",
  "zotero-agent-settings-onboarding-option-api-key-help",
  "zotero-agent-settings-onboarding-option-custom",
  "zotero-agent-settings-onboarding-option-custom-help",
  "zotero-agent-settings-onboarding-no-connection",
  "zotero-agent-settings-onboarding-connection-count",
  "zotero-agent-settings-onboarding-model-count",
  "zotero-agent-settings-onboarding-current-default",
  "zotero-agent-settings-onboarding-no-default",
  "zotero-agent-settings-onboarding-manage-connections",
  "zotero-agent-settings-onboarding-choose-model-action",
  "zotero-agent-settings-onboarding-mcp",
  "zotero-agent-settings-onboarding-mcp-help",
  "zotero-agent-settings-onboarding-mcp-action",
  "zotero-agent-settings-onboarding-search",
  "zotero-agent-settings-onboarding-search-help",
  "zotero-agent-settings-onboarding-search-action",
  "zotero-agent-settings-onboarding-close",
  "zotero-agent-settings-onboarding-progress",
  // Connections
  "zotero-agent-settings-connections-title",
  "zotero-agent-settings-connections-subtitle",
  "zotero-agent-settings-connections-add",
  "zotero-agent-settings-connections-empty",
  "zotero-agent-settings-connections-loaded",
  "zotero-agent-settings-connections-manage",
  "zotero-agent-settings-connections-switch",
  "zotero-agent-settings-connection-section-account",
  "zotero-agent-settings-connection-section-service",
  "zotero-agent-settings-connection-section-auth",
  "zotero-agent-settings-connection-label",
  "zotero-agent-settings-connection-provider",
  "zotero-agent-settings-connection-edit",
  "zotero-agent-settings-connection-remove",
  "zotero-agent-settings-connection-save",
  "zotero-agent-settings-connection-saved",
  "zotero-agent-settings-connection-removed",
  "zotero-agent-settings-connection-base-url",
  "zotero-agent-settings-connection-dialect",
  "zotero-agent-settings-connection-parameters",
  "zotero-agent-settings-connection-account-id",
  "zotero-agent-settings-connection-gateway-id",
  "zotero-agent-settings-connection-allow-local",
  "zotero-agent-settings-local-network-title",
  "zotero-agent-settings-local-network-body",
  "zotero-agent-settings-connection-target-confirm",
  "zotero-agent-settings-connection-target-help",
  "zotero-agent-settings-connection-status-signed-out",
  "zotero-agent-settings-connection-status-needs-auth",
  "zotero-agent-settings-connection-status-target",
  "zotero-agent-settings-connection-status-local",
  "zotero-agent-settings-connection-status-disabled",
  "zotero-agent-settings-connection-provider-preset",
  "zotero-agent-settings-connection-provider-add",
  "zotero-agent-settings-connection-gap-login",
  "zotero-agent-settings-connection-gap-request",
  "zotero-agent-settings-connection-gap-adapter",
  // Credentials
  "zotero-agent-settings-credential-label",
  "zotero-agent-settings-credential-secret",
  "zotero-agent-settings-credential-replace",
  "zotero-agent-settings-credential-save",
  "zotero-agent-settings-credential-saved-keep",
  "zotero-agent-settings-credential-scope",
  "zotero-agent-settings-credential-clear",
  "zotero-agent-settings-credential-missing",
  "zotero-agent-settings-credential-not-required",
  "zotero-agent-settings-credential-shared-kept",
  "zotero-agent-settings-credential-exclusive-cleared",
  // ChatGPT registrations
  "zotero-agent-settings-chatgpt-title",
  "zotero-agent-settings-chatgpt-subtitle",
  "zotero-agent-settings-chatgpt-connect",
  "zotero-agent-settings-chatgpt-connect-new",
  "zotero-agent-settings-chatgpt-relogin",
  "zotero-agent-settings-chatgpt-registrations",
  "zotero-agent-settings-chatgpt-workspace",
  "zotero-agent-settings-chatgpt-registration-label",
  "zotero-agent-settings-chatgpt-registration-label-help",
  "zotero-agent-settings-chatgpt-progress-waiting",
  "zotero-agent-settings-chatgpt-progress-exchange",
  "zotero-agent-settings-chatgpt-progress-verify",
  "zotero-agent-settings-chatgpt-progress-expired",
  "zotero-agent-settings-chatgpt-progress-failed",
  "zotero-agent-settings-chatgpt-cancel",
  "zotero-agent-settings-chatgpt-privacy",
  "zotero-agent-settings-chatgpt-welcome-title",
  "zotero-agent-settings-chatgpt-welcome-body",
  "zotero-agent-settings-chatgpt-welcome-accept",
  "zotero-agent-settings-chatgpt-welcome-state",
  "zotero-agent-settings-chatgpt-plan-enabled",
  "zotero-agent-settings-chatgpt-plan-unavailable",
  "zotero-agent-settings-chatgpt-plan-welcome-pending",
  "zotero-agent-settings-chatgpt-plan-reconsent",
  "zotero-agent-settings-chatgpt-plan-reconsent-help",
  "zotero-agent-settings-chatgpt-plan-reconsent-action",
  "zotero-agent-settings-chatgpt-paused",
  "zotero-agent-settings-chatgpt-paused-help",
  "zotero-agent-settings-chatgpt-usage",
  "zotero-agent-settings-chatgpt-usage-help",
  "zotero-agent-settings-chatgpt-resume-help",
  "zotero-agent-settings-chatgpt-signed-out",
  "zotero-agent-settings-chatgpt-sign-out",
  "zotero-agent-settings-chatgpt-remove",
  "zotero-agent-settings-chatgpt-remove-registration",
  "zotero-agent-settings-chatgpt-revoked",
  "zotero-agent-settings-chatgpt-revoke-unknown",
  "zotero-agent-settings-chatgpt-rebind",
  "zotero-agent-settings-chatgpt-rebind-action",
  "zotero-agent-settings-chatgpt-canceled-kept",
  "zotero-agent-settings-chatgpt-completed-kept",
  "zotero-agent-settings-chatgpt-edit-canceled",
  "zotero-agent-settings-chatgpt-window-closed",
  // Model cards and default purposes
  "zotero-agent-settings-models-title",
  "zotero-agent-settings-models-subtitle",
  "zotero-agent-settings-models-add",
  "zotero-agent-settings-models-adding",
  "zotero-agent-settings-models-empty",
  "zotero-agent-settings-models-remove",
  "zotero-agent-settings-models-reasoning",
  "zotero-agent-settings-models-reasoning-level",
  "zotero-agent-settings-models-reasoning-unknown",
  "zotero-agent-settings-models-reasoning-unsupported",
  "zotero-agent-settings-models-reasoning-selectable",
  "zotero-agent-settings-models-defaults",
  "zotero-agent-settings-models-defaults-hint",
  "zotero-agent-settings-models-default-general",
  "zotero-agent-settings-models-default-conversation",
  "zotero-agent-settings-models-default-skill-run",
  "zotero-agent-settings-models-default-titles",
  "zotero-agent-settings-models-default-current",
  "zotero-agent-settings-models-defaults-current",
  "zotero-agent-settings-models-default-inherit",
  "zotero-agent-settings-models-default-titles-off",
  "zotero-agent-settings-models-default-click-off",
  "zotero-agent-settings-models-default-click-inherit",
  "zotero-agent-settings-models-default-click-set",
  "zotero-agent-settings-models-default-titles-use",
  "zotero-agent-settings-models-default-titles-unavailable",
  "zotero-agent-settings-models-default-unset",
  "zotero-agent-settings-models-default-titles-disabled",
  "zotero-agent-settings-models-default-inherit-restored",
  "zotero-agent-settings-models-no-general-default",
  "zotero-agent-settings-models-need-sign-in",
  "zotero-agent-settings-models-after-save",
  "zotero-agent-settings-models-insufficient",
  "zotero-agent-settings-models-discovery-empty",
  "zotero-agent-settings-models-discovering",
  "zotero-agent-settings-models-discovery-failed",
  "zotero-agent-settings-models-discovery-done",
  "zotero-agent-settings-models-discovery-retained",
  "zotero-agent-settings-models-directory-add",
  "zotero-agent-settings-models-overlay-applied",
  "zotero-agent-settings-models-overlay-note",
  "zotero-agent-settings-models-refresh",
  "zotero-agent-settings-models-search",
  "zotero-agent-settings-models-unavailable",
  "zotero-agent-settings-models-missing-default",
  "zotero-agent-settings-models-back",
  // Model and source tests
  "zotero-agent-settings-test-model",
  "zotero-agent-settings-test-model-resume",
  "zotero-agent-settings-test-confirm-title",
  "zotero-agent-settings-test-confirm-body",
  "zotero-agent-settings-test-confirm-source-title",
  "zotero-agent-settings-test-confirm-source-mcp",
  "zotero-agent-settings-test-confirm-source-search",
  "zotero-agent-settings-test-confirm-billable",
  "zotero-agent-settings-test-running",
  "zotero-agent-settings-test-completed",
  "zotero-agent-settings-test-resumed",
  "zotero-agent-settings-test-incomplete",
  "zotero-agent-settings-test-not-completed",
  "zotero-agent-settings-test-untested",
  // MCP page
  "zotero-agent-settings-mcp-title",
  "zotero-agent-settings-mcp-subtitle",
  "zotero-agent-settings-mcp-add",
  "zotero-agent-settings-mcp-add-source",
  "zotero-agent-settings-mcp-add-help",
  "zotero-agent-settings-mcp-empty",
  "zotero-agent-settings-mcp-corrupt",
  "zotero-agent-settings-mcp-source-title",
  "zotero-agent-settings-mcp-source-name",
  "zotero-agent-settings-mcp-source-transport",
  "zotero-agent-settings-mcp-transport-stdio",
  "zotero-agent-settings-mcp-transport-http",
  "zotero-agent-settings-mcp-executable",
  "zotero-agent-settings-mcp-endpoint",
  "zotero-agent-settings-mcp-argv",
  "zotero-agent-settings-mcp-argv-add",
  "zotero-agent-settings-mcp-argv-help",
  "zotero-agent-settings-mcp-argv-item",
  "zotero-agent-settings-mcp-argv-remove",
  "zotero-agent-settings-mcp-argv-single",
  "zotero-agent-settings-mcp-argv-invalid",
  "zotero-agent-settings-mcp-cwd",
  "zotero-agent-settings-mcp-cwd-placeholder",
  "zotero-agent-settings-mcp-cwd-help",
  "zotero-agent-settings-mcp-env",
  "zotero-agent-settings-mcp-env-add",
  "zotero-agent-settings-mcp-env-name",
  "zotero-agent-settings-mcp-allow-local",
  "zotero-agent-settings-mcp-auth",
  "zotero-agent-settings-mcp-auth-kind",
  "zotero-agent-settings-mcp-auth-none",
  "zotero-agent-settings-mcp-auth-bearer",
  "zotero-agent-settings-mcp-auth-api-key",
  "zotero-agent-settings-mcp-auth-custom",
  "zotero-agent-settings-mcp-auth-field",
  "zotero-agent-settings-mcp-binding-field",
  "zotero-agent-settings-mcp-auth-token",
  "zotero-agent-settings-mcp-auth-token-help",
  "zotero-agent-settings-mcp-auth-key-help",
  "zotero-agent-settings-mcp-auth-token-required",
  "zotero-agent-settings-mcp-auth-key-required",
  "zotero-agent-settings-mcp-auth-field-required",
  "zotero-agent-settings-mcp-auth-field-duplicate",
  "zotero-agent-settings-mcp-auth-field-type",
  "zotero-agent-settings-mcp-auth-field-common",
  "zotero-agent-settings-mcp-auth-field-custom",
  "zotero-agent-settings-mcp-auth-field-custom-placeholder",
  "zotero-agent-settings-mcp-headers",
  "zotero-agent-settings-mcp-headers-help",
  "zotero-agent-settings-mcp-headers-add",
  "zotero-agent-settings-mcp-header-invalid",
  "zotero-agent-settings-mcp-save-source",
  "zotero-agent-settings-mcp-save-hint",
  "zotero-agent-settings-mcp-saved",
  "zotero-agent-settings-mcp-enabled",
  "zotero-agent-settings-mcp-save-enabled",
  "zotero-agent-settings-mcp-auth-pending",
  "zotero-agent-settings-mcp-test",
  "zotero-agent-settings-mcp-edit-source",
  "zotero-agent-settings-mcp-remove-source",
  "zotero-agent-settings-mcp-remove-title",
  "zotero-agent-settings-mcp-remove-body",
  "zotero-agent-settings-mcp-remove-confirm",
  "zotero-agent-settings-mcp-removed",
  "zotero-agent-settings-mcp-remove-no-purpose",
  "zotero-agent-settings-mcp-json-edit",
  "zotero-agent-settings-mcp-json-import",
  "zotero-agent-settings-mcp-json-export",
  "zotero-agent-settings-mcp-json-title",
  "zotero-agent-settings-mcp-json-save",
  "zotero-agent-settings-mcp-json-merge-save",
  "zotero-agent-settings-mcp-json-invalid",
  "zotero-agent-settings-mcp-json-import-help",
  "zotero-agent-settings-mcp-json-edit-help",
  "zotero-agent-settings-mcp-json-export-help",
  "zotero-agent-settings-mcp-json-replace",
  "zotero-agent-settings-mcp-json-replace-body",
  "zotero-agent-settings-mcp-json-conflicts",
  "zotero-agent-settings-mcp-json-grant-local",
  "zotero-agent-settings-mcp-json-grant-body",
  "zotero-agent-settings-mcp-json-impact",
  "zotero-agent-settings-mcp-json-secret-slots",
  "zotero-agent-settings-mcp-json-problems",
  "zotero-agent-settings-mcp-json-remove-missing",
  "zotero-agent-settings-mcp-json-error-object",
  "zotero-agent-settings-mcp-json-error-argv",
  "zotero-agent-settings-mcp-json-error-servers",
  "zotero-agent-settings-mcp-json-error-name",
  "zotero-agent-settings-mcp-json-error-unsupported",
  "zotero-agent-settings-mcp-json-error-target",
  "zotero-agent-settings-mcp-json-error-shape",
  "zotero-agent-settings-mcp-no-connection",
  // Search page
  "zotero-agent-settings-search-title",
  "zotero-agent-settings-search-subtitle",
  "zotero-agent-settings-search-save",
  "zotero-agent-settings-search-save-hint",
  "zotero-agent-settings-search-saved",
  "zotero-agent-settings-search-save-order",
  "zotero-agent-settings-search-order-saved",
  "zotero-agent-settings-search-enabled",
  "zotero-agent-settings-search-save-enabled",
  "zotero-agent-settings-search-enabled-saved",
  "zotero-agent-settings-search-disabled-saved",
  "zotero-agent-settings-search-configure",
  "zotero-agent-settings-search-needs-config",
  "zotero-agent-settings-search-billable",
  "zotero-agent-settings-search-billable-notice",
  "zotero-agent-settings-search-billable-warning",
  "zotero-agent-settings-search-move-up",
  "zotero-agent-settings-search-move-down",
  "zotero-agent-settings-search-test",
  "zotero-agent-settings-search-test-running",
  "zotero-agent-settings-search-test-completed",
  "zotero-agent-settings-search-test-available",
  "zotero-agent-settings-search-test-incomplete",
  "zotero-agent-settings-search-test-failed",
  "zotero-agent-settings-search-test-untested",
  "zotero-agent-settings-search-connection",
  "zotero-agent-settings-search-connection-help",
  "zotero-agent-settings-search-model",
  "zotero-agent-settings-search-model-help",
  "zotero-agent-settings-search-model-select",
  "zotero-agent-settings-search-endpoint",
  "zotero-agent-settings-search-allow-local",
  "zotero-agent-settings-search-key",
  "zotero-agent-settings-search-key-replace",
  "zotero-agent-settings-search-key-saved",
  "zotero-agent-settings-search-key-scope",
  "zotero-agent-settings-search-executable",
  "zotero-agent-settings-search-args",
  "zotero-agent-settings-search-unsaved-title",
  "zotero-agent-settings-search-unsaved-body",
  "zotero-agent-settings-search-exa-note",
  "zotero-agent-settings-search-no-connection",
  // Catalog and maintenance
  "zotero-agent-settings-catalog-title",
  "zotero-agent-settings-catalog-subtitle",
  "zotero-agent-settings-catalog-providers",
  "zotero-agent-settings-catalog-summary",
  "zotero-agent-settings-catalog-models-count",
  "zotero-agent-settings-catalog-provider",
  "zotero-agent-settings-catalog-provider-all",
  "zotero-agent-settings-catalog-provider-requires-parameters",
  "zotero-agent-settings-catalog-provider-not-configurable",
  "zotero-agent-settings-catalog-provider-preset",
  "zotero-agent-settings-catalog-directory",
  "zotero-agent-settings-catalog-search",
  "zotero-agent-settings-catalog-empty",
  "zotero-agent-settings-catalog-prev",
  "zotero-agent-settings-catalog-next",
  "zotero-agent-settings-catalog-context-unknown",
  "zotero-agent-settings-catalog-version",
  "zotero-agent-settings-catalog-refresh",
  "zotero-agent-settings-catalog-add",
  "zotero-agent-settings-catalog-added",
  "zotero-agent-settings-catalog-add-disabled",
  "zotero-agent-settings-catalog-configurable",
  "zotero-agent-settings-catalog-configurable-parameters",
  "zotero-agent-settings-catalog-retired",
  "zotero-agent-settings-catalog-maintenance-actions",
  "zotero-agent-settings-catalog-public",
  "zotero-agent-settings-catalog-public-help",
  "zotero-agent-settings-catalog-auto-update",
  "zotero-agent-settings-catalog-auto-update-save",
  "zotero-agent-settings-catalog-check-now",
  "zotero-agent-settings-catalog-checked",
  "zotero-agent-settings-catalog-restore",
  "zotero-agent-settings-catalog-restore-help",
  "zotero-agent-settings-catalog-restored",
  "zotero-agent-settings-catalog-unavailable",
  "zotero-agent-settings-catalog-overlay",
  "zotero-agent-settings-catalog-overlay-import",
  "zotero-agent-settings-catalog-overlay-refresh",
  "zotero-agent-settings-catalog-overlay-remove",
  "zotero-agent-settings-catalog-overlay-none",
  "zotero-agent-settings-catalog-overlay-adopted",
  "zotero-agent-settings-catalog-overlay-result",
  "zotero-agent-settings-catalog-overlay-missing",
  "zotero-agent-settings-catalog-overlay-removed",
  "zotero-agent-settings-catalog-diagnostics",
  "zotero-agent-settings-catalog-diagnostics-help",
  "zotero-agent-settings-catalog-export-diagnostics",
  "zotero-agent-settings-catalog-export-canceled",
  "zotero-agent-settings-catalog-export-done",
  "zotero-agent-settings-catalog-loading",
  "zotero-agent-settings-catalog-ready",
  "zotero-agent-settings-catalog-error",
  // Removal confirmations
  "zotero-agent-settings-remove-model-title",
  "zotero-agent-settings-remove-model-body",
  "zotero-agent-settings-remove-model-confirm",
  "zotero-agent-settings-remove-model-kept",
  "zotero-agent-settings-remove-no-purpose",
  "zotero-agent-settings-remove-connection-title",
  "zotero-agent-settings-remove-connection-body",
  "zotero-agent-settings-remove-connection-cards",
  "zotero-agent-settings-remove-connection-registration-kept",
  "zotero-agent-settings-remove-connection-key-kept",
  "zotero-agent-settings-remove-connection-key-cleared",
  "zotero-agent-settings-remove-connection-tasks",
  "zotero-agent-settings-remove-connection-keep",
  "zotero-agent-settings-remove-connection-confirm",
  "zotero-agent-settings-remove-registration-body",
] as const satisfies readonly FluentMessageId[];

export type ZoteroAgentSettingsLabelKey =
  (typeof ZOTERO_AGENT_SETTINGS_LABEL_KEYS)[number];

/**
 * Keys whose FTL value interpolates arguments. The labels record is a flat
 * string map, so these cannot be projected: a page that needs one has to ask
 * the host for a formatted value rather than receive an unresolved pattern.
 */
export const ZOTERO_AGENT_SETTINGS_PARAMETERIZED_LABEL_KEYS = [
  "zotero-agent-settings-local-network-body",
  "zotero-agent-settings-local-network-title",
  "zotero-agent-settings-entry-remove",
  "zotero-agent-settings-onboarding-connection-count",
  "zotero-agent-settings-onboarding-model-count",
  "zotero-agent-settings-models-overlay-applied",
  "zotero-agent-settings-mcp-argv-item",
  "zotero-agent-settings-mcp-argv-remove",
  "zotero-agent-settings-mcp-remove-body",
  "zotero-agent-settings-mcp-json-replace-body",
  "zotero-agent-settings-mcp-json-grant-body",
  "zotero-agent-settings-mcp-json-impact",
  "zotero-agent-settings-mcp-json-secret-slots",
  "zotero-agent-settings-search-test-available",
  "zotero-agent-settings-catalog-summary",
  "zotero-agent-settings-catalog-models-count",
  "zotero-agent-settings-catalog-version",
  "zotero-agent-settings-catalog-overlay-result",
  "zotero-agent-settings-remove-model-body",
  "zotero-agent-settings-remove-connection-body",
] as const satisfies readonly ZoteroAgentSettingsLabelKey[];

/** Page-facing camelCase key -> FTL message id. The only such mapping. */
export const ZOTERO_AGENT_SETTINGS_PAGE_LABEL_ALIASES = {
  agentName: "backend-manager-pi-title",
  savingConnection: "zotero-agent-settings-status-saving",
  savingMcpSource: "zotero-agent-settings-status-saving",
  savingMcpDocument: "zotero-agent-settings-status-saving",
  savingWebSource: "zotero-agent-settings-status-saving",
  connectionSaved: "zotero-agent-settings-connection-saved",
  connectionRemoved: "zotero-agent-settings-connection-removed",
  mcpSourceSaved: "zotero-agent-settings-mcp-saved",
  mcpDocumentSaved: "zotero-agent-settings-mcp-saved",
  webSourceSaved: "zotero-agent-settings-search-saved",
  testIncomplete: "zotero-agent-settings-test-incomplete",
  modelRemoved: "zotero-agent-settings-remove-model-kept",
  diagnosticsExported: "zotero-agent-settings-catalog-export-done",
  catalogRestored: "zotero-agent-settings-catalog-restored",
  catalogUpdated: "zotero-agent-settings-catalog-checked",
  testBadgeCompleted: "zotero-agent-settings-test-completed",
  testPossibleUsage: "zotero-agent-settings-test-confirm-billable",
  accountNoPlan: "zotero-agent-settings-chatgpt-plan-unavailable",
  reauthorize: "zotero-agent-settings-chatgpt-plan-reconsent-action",
  accountWelcomeHelp: "zotero-agent-settings-chatgpt-welcome-body",
  acceptPlan: "zotero-agent-settings-chatgpt-welcome-accept",
  accountReauthorizeTitle: "zotero-agent-settings-chatgpt-plan-reconsent",
  accountReauthorizeHelp: "zotero-agent-settings-chatgpt-plan-reconsent-help",
  accountPausedTitle: "zotero-agent-settings-chatgpt-paused",
  accountPausedHelp: "zotero-agent-settings-chatgpt-paused-help",
  accountNone: "zotero-agent-settings-connection-status-signed-out",
  refreshDirectory: "zotero-agent-settings-catalog-refresh",
  searchNeedsConfig: "zotero-agent-settings-search-needs-config",
  providerNeedsParameters:
    "zotero-agent-settings-catalog-provider-requires-parameters",
  providerPreset: "zotero-agent-settings-connection-provider-preset",
  providerAddConnection: "zotero-agent-settings-connection-provider-add",
  registrationNew: "zotero-agent-settings-chatgpt-connect-new",
  registrationIdentityHelp:
    "zotero-agent-settings-chatgpt-registration-label-help",
  allowLocalService: "zotero-agent-settings-connection-allow-local",
  apiKey: "zotero-agent-settings-credential-secret",
  keyHelp: "zotero-agent-settings-credential-scope",
  editorHintKey: "zotero-agent-settings-models-after-save",
  discard: "zotero-agent-settings-action-discard",
  bindingSavedPlaceholder: "zotero-agent-settings-field-keep-saved",
  bindingPlaceholder: "zotero-agent-settings-field-value-required",
  mcpAddress: "zotero-agent-settings-mcp-endpoint",
  mcpArgHelp: "zotero-agent-settings-mcp-argv-help",
  mcpCwdHelp: "zotero-agent-settings-mcp-cwd-help",
  mcpCwdEmptyHelp: "zotero-agent-settings-mcp-cwd-help",
  mcpAuth: "zotero-agent-settings-mcp-auth-kind",
  authApiKeyCustom: "zotero-agent-settings-mcp-auth-field-custom",
  authApiKeyField: "zotero-agent-settings-mcp-auth-field",
  authToken: "zotero-agent-settings-mcp-auth-token",
  authApiKey: "zotero-agent-settings-mcp-auth-api-key",
  authTokenHelp: "zotero-agent-settings-mcp-auth-token-help",
  authApiKeyHelp: "zotero-agent-settings-mcp-auth-key-help",
  mcpHeaders: "zotero-agent-settings-mcp-headers-help",
  mcpEditorHint: "zotero-agent-settings-mcp-save-hint",
  webNativeNote: "zotero-agent-settings-search-model-help",
  webExaNote: "zotero-agent-settings-search-exa-note",
  webConnection: "zotero-agent-settings-search-connection",
  webNoCompatibleConnection: "zotero-agent-settings-search-no-connection",
  webEndpoint: "zotero-agent-settings-search-endpoint",
  searchKeyHelp: "zotero-agent-settings-search-key-scope",
  webEditorHint: "zotero-agent-settings-search-save-hint",
  testBillableWarning: "zotero-agent-settings-test-confirm-billable",
  backToWorkbench: "zotero-agent-settings-models-back",
  pickerCounts: "zotero-agent-settings-models-missing-default",
  keepModel: "zotero-agent-settings-action-cancel",
  confirmRemove: "zotero-agent-settings-action-confirm",
  authCanceled: "zotero-agent-settings-chatgpt-canceled-kept",
  welcomeAccepted: "zotero-agent-settings-chatgpt-welcome-state",
  usageOpening: "zotero-agent-settings-chatgpt-usage-help",
  testRunning: "zotero-agent-settings-test-running",
  authWaiting: "zotero-agent-settings-chatgpt-progress-waiting",
  navOverview: "zotero-agent-settings-nav-onboarding",
  navSearch: "zotero-agent-settings-nav-search",
  navCatalog: "zotero-agent-settings-nav-maintenance",
  heroReady: "zotero-agent-settings-onboarding-ready",
  heroFinish: "zotero-agent-settings-onboarding-pending",
  heroEmptyHelp: "zotero-agent-settings-onboarding-choose-service",
  heroReadyHelp: "zotero-agent-settings-onboarding-adjust-later",
  heroFinishHelp: "zotero-agent-settings-onboarding-choose-model",
  stepModel: "zotero-agent-settings-onboarding-step-model",
  setupChatgpt: "zotero-agent-settings-onboarding-option-chatgpt",
  setupChatgptHelp: "zotero-agent-settings-onboarding-option-chatgpt-help",
  setupApiKey: "zotero-agent-settings-onboarding-option-api-key",
  setupApiKeyHelp: "zotero-agent-settings-onboarding-option-api-key-help",
  setupCustomHelp: "zotero-agent-settings-onboarding-option-custom-help",
  manageConnections: "zotero-agent-settings-onboarding-manage-connections",
  taskGeneral: "zotero-agent-settings-onboarding-current-default",
  taskGeneralEmpty: "zotero-agent-settings-onboarding-no-default",
  adjustModel: "zotero-agent-settings-onboarding-choose-model-action",
  chooseModel: "zotero-agent-settings-onboarding-step-model",
  taskMcp: "zotero-agent-settings-onboarding-mcp",
  taskSearch: "zotero-agent-settings-onboarding-search",
  addConnection: "zotero-agent-settings-connections-add",
  workbenchEmptyHelp: "zotero-agent-settings-onboarding-subtitle",
  workbenchEmptyOther: "zotero-agent-settings-connections-add",
  purposeGeneral: "zotero-agent-settings-models-default-general",
  purposeConversation: "zotero-agent-settings-models-default-conversation",
  purposeSkillRun: "zotero-agent-settings-models-default-skill-run",
  purposeTitle: "zotero-agent-settings-models-default-titles",
  purposeFollowsGeneral: "zotero-agent-settings-models-default-inherit",
  purposeCurrentGeneral: "zotero-agent-settings-models-default-current",
  purposeDisableTitle: "zotero-agent-settings-models-default-click-off",
  purposeInherit: "zotero-agent-settings-models-default-click-inherit",
  purposeEnableTitle: "zotero-agent-settings-models-default-titles-use",
  purposeHelp: "zotero-agent-settings-models-defaults-hint",
  titlesOff: "zotero-agent-settings-models-default-titles-off",
  notChosen: "zotero-agent-settings-label-unset",
  reasoning: "zotero-agent-settings-models-reasoning",
  detailAuth: "zotero-agent-settings-connection-section-auth",
  authNoKey: "zotero-agent-settings-credential-not-required",
  authKeyMissing: "zotero-agent-settings-credential-missing",
  modelsHintApi: "zotero-agent-settings-models-directory-add",
  modelsHintChatgpt: "zotero-agent-settings-models-need-sign-in",
  repairTitle: "zotero-agent-settings-connection-status-target",
  repairHelp: "zotero-agent-settings-connection-target-help",
  mcpTitle: "zotero-agent-settings-mcp-title",
  mcpDisabled: "zotero-agent-settings-connection-status-disabled",
  mcpHelp: "zotero-agent-settings-mcp-subtitle",
  addMcpSource: "zotero-agent-settings-mcp-add-source",
  mcpEmptyTitle: "zotero-agent-settings-mcp-empty",
  mcpEmptyHelp: "zotero-agent-settings-mcp-subtitle",
  removeSource: "zotero-agent-settings-mcp-remove-confirm",
  searchTitle: "zotero-agent-settings-search-title",
  searchHelp: "zotero-agent-settings-search-subtitle",
  searchNeedsConfiguration: "zotero-agent-settings-search-needs-config",
  catalogTitle: "zotero-agent-settings-catalog-title",
  catalogReady: "zotero-agent-settings-catalog-ready",
  maintenanceExportOnly: "zotero-agent-settings-catalog-export-diagnostics",
  catalogHelp: "zotero-agent-settings-catalog-subtitle",
  catalogEmpty: "zotero-agent-settings-catalog-empty",
  catalogContextUnknown: "zotero-agent-settings-catalog-context-unknown",
  catalogBadgeParameters:
    "zotero-agent-settings-catalog-configurable-parameters",
  catalogBadgeNotConfigurable: "zotero-agent-settings-catalog-add-disabled",
  catalogNotConfigurable: "zotero-agent-settings-catalog-add-disabled",
  catalogAdd: "zotero-agent-settings-catalog-add",
  maintenanceDirectory: "zotero-agent-settings-catalog-public",
  maintenanceDirectoryHelp: "zotero-agent-settings-catalog-public-help",
  maintenanceOverlay: "zotero-agent-settings-catalog-overlay",
  maintenanceOverlayNone: "zotero-agent-settings-catalog-overlay-none",
  maintenanceOverlayAdopted: "zotero-agent-settings-catalog-overlay-adopted",
  maintenanceRemoveOverlay: "zotero-agent-settings-catalog-overlay-remove",
  maintenanceAutoUpdate: "zotero-agent-settings-catalog-auto-update",
  maintenanceRestoreHint: "zotero-agent-settings-catalog-restore-help",
  maintenanceDiagnostics: "zotero-agent-settings-catalog-diagnostics",
  maintenanceDiagnosticsHelp: "zotero-agent-settings-catalog-diagnostics-help",
  testBadgeIncomplete: "zotero-agent-settings-test-not-completed",
  testAndResume: "zotero-agent-settings-test-model-resume",
  testModel: "zotero-agent-settings-test-model",
  accountWelcomeTitle: "zotero-agent-settings-chatgpt-welcome-title",
  accountSignedIn: "zotero-agent-settings-chatgpt-plan-enabled",
  accountSignedOut: "zotero-agent-settings-chatgpt-signed-out",
  cancelAuth: "zotero-agent-settings-chatgpt-cancel",
  reconnectChatgpt: "zotero-agent-settings-chatgpt-rebind-action",
  connectChatgpt: "zotero-agent-settings-chatgpt-connect",
  detailService: "zotero-agent-settings-connection-section-service",
  refreshModels: "zotero-agent-settings-models-refresh",
  navGroupModels: "zotero-agent-settings-nav-section-models",
  navWorkbench: "zotero-agent-settings-nav-models",
  navGroupExtensions: "zotero-agent-settings-nav-section-extensions",
  navGroupAdvanced: "zotero-agent-settings-nav-section-advanced",
  heroEmpty: "zotero-agent-settings-onboarding-title",
  stepConnect: "zotero-agent-settings-onboarding-step-connect",
  stepUse: "zotero-agent-settings-onboarding-step-use",
  taskConnections: "zotero-agent-settings-connections-title",
  taskMcpHelp: "zotero-agent-settings-onboarding-mcp-help",
  configureMcp: "zotero-agent-settings-onboarding-mcp-action",
  taskSearchHelp: "zotero-agent-settings-onboarding-search-help",
  configureSearch: "zotero-agent-settings-onboarding-search-action",
  setupCustom: "zotero-agent-settings-onboarding-option-custom",
  workbenchTitle: "zotero-agent-settings-nav-models",
  workbenchHelp: "zotero-agent-settings-connections-subtitle",
  workbenchEmptyTitle: "zotero-agent-settings-onboarding-no-connection",
  workbenchEmptyChatgpt: "zotero-agent-settings-chatgpt-connect",
  transportStdio: "zotero-agent-settings-mcp-transport-stdio",
  editSource: "zotero-agent-settings-mcp-edit-source",
  mcpJsonEdit: "zotero-agent-settings-mcp-json-edit",
  mcpJsonImport: "zotero-agent-settings-mcp-json-import",
  mcpJsonExport: "zotero-agent-settings-mcp-json-export",
  addMcpSourceAction: "zotero-agent-settings-mcp-add-source",
  configureSource: "zotero-agent-settings-search-configure",
  testSource: "zotero-agent-settings-search-test",
  catalogBadgeConfigurable: "zotero-agent-settings-catalog-configurable",
  catalogBadgeRetired: "zotero-agent-settings-catalog-retired",
  catalogAdded: "zotero-agent-settings-catalog-added",
  maintenanceCheck: "zotero-agent-settings-catalog-check-now",
  maintenanceRestore: "zotero-agent-settings-catalog-restore",
  maintenanceImport: "zotero-agent-settings-catalog-overlay-import",
  maintenanceRefreshFile: "zotero-agent-settings-catalog-overlay-refresh",
  maintenanceExport: "zotero-agent-settings-catalog-export-diagnostics",
  catalogAllProviders: "zotero-agent-settings-catalog-provider-all",
  providerField: "zotero-agent-settings-connection-provider",
  registrationIdentity: "zotero-agent-settings-chatgpt-registration-label",
  keyless: "zotero-agent-settings-credential-not-required",
  replaceKey: "zotero-agent-settings-credential-replace",
  keySavedPlaceholder: "zotero-agent-settings-field-keep-saved",
  saveConnection: "zotero-agent-settings-connection-save",
  cancel: "zotero-agent-settings-action-cancel",
  removeEntry: "zotero-agent-settings-action-remove",
  mcpEditorTitle: "zotero-agent-settings-mcp-source-title",
  mcpEditorAddTitle: "zotero-agent-settings-mcp-add-source",
  mcpExecutable: "zotero-agent-settings-mcp-executable",
  addArg: "zotero-agent-settings-mcp-argv-add",
  mcpCwdPlaceholder: "zotero-agent-settings-mcp-cwd-placeholder",
  mcpEnv: "zotero-agent-settings-mcp-env",
  allowLocalTool: "zotero-agent-settings-mcp-allow-local",
  authNone: "zotero-agent-settings-mcp-auth-none",
  saveMcpSource: "zotero-agent-settings-mcp-save-source",
  webPickConnection: "zotero-agent-settings-search-connection-help",
  webModel: "zotero-agent-settings-search-model",
  webPickModel: "zotero-agent-settings-search-model-select",
  allowLocalSearch: "zotero-agent-settings-search-allow-local",
  webExecutable: "zotero-agent-settings-search-executable",
  webArgs: "zotero-agent-settings-search-args",
  replaceSearchKey: "zotero-agent-settings-search-key-replace",
  searchKey: "zotero-agent-settings-search-key",
  saveWebSource: "zotero-agent-settings-search-save",
  sendTest: "zotero-agent-settings-test-confirm-title",
  continueEditing: "zotero-agent-settings-action-continue-editing",
  discardChanges: "zotero-agent-settings-action-discard",
  saveAndClose: "zotero-agent-settings-action-save-and-close",
  saveAndSwitch: "zotero-agent-settings-action-save-and-continue",
  saveAndReturn: "zotero-agent-settings-action-save-and-return",
  confirmRemoveModel: "zotero-agent-settings-remove-model-title",
  confirmRemoveSource: "zotero-agent-settings-mcp-remove-title",
  confirmRemoveRegistration:
    "zotero-agent-settings-chatgpt-remove-registration",
  confirmSignOut: "zotero-agent-settings-chatgpt-sign-out",
  confirmRemoveConnection: "zotero-agent-settings-remove-connection-title",
  keepConnection: "zotero-agent-settings-remove-connection-keep",
  connectionProvider: "zotero-agent-settings-connection-provider",
  acceptTarget: "zotero-agent-settings-connection-target-confirm",
  accountAndLogin: "zotero-agent-settings-connection-section-account",
  accountConnect: "zotero-agent-settings-chatgpt-title",
  addModel: "zotero-agent-settings-models-add",
  cardOverlay: "zotero-agent-settings-models-overlay-note",
  addingModel: "zotero-agent-settings-models-adding",
  advancedHeaders: "zotero-agent-settings-mcp-headers",
  apiKeyType: "zotero-agent-settings-mcp-auth-field-type",
  argLabel: "zotero-agent-settings-mcp-argv-single",
  argsInvalid: "zotero-agent-settings-mcp-json-error-argv",
  argvLabel: "zotero-agent-settings-mcp-argv",
  billableNote: "zotero-agent-settings-search-billable-warning",
  bindingField: "zotero-agent-settings-mcp-binding-field",
  bindingValue: "zotero-agent-settings-field-value",
  catalogBrowse: "zotero-agent-settings-catalog-providers",
  catalogProvider: "zotero-agent-settings-catalog-provider",
  catalogSearch: "zotero-agent-settings-catalog-search",
  connectionLabel: "zotero-agent-settings-connection-label",
  connectionListLabel: "zotero-agent-settings-connections-title",
  currentDefaultsLabel: "zotero-agent-settings-models-defaults-current",
  cwdLabel: "zotero-agent-settings-mcp-cwd",
  dialectField: "zotero-agent-settings-connection-dialect",
  editConnection: "zotero-agent-settings-connection-edit",
  enabled: "zotero-agent-settings-mcp-enabled",
  endpointField: "zotero-agent-settings-mcp-endpoint",
  jsonConflicts: "zotero-agent-settings-mcp-json-conflicts",
  manageUsage: "zotero-agent-settings-chatgpt-usage",
  mcpNeedsSecret: "zotero-agent-settings-mcp-auth-pending",
  modelsAndPurposes: "zotero-agent-settings-models-title",
  moveDown: "zotero-agent-settings-search-move-down",
  moveUp: "zotero-agent-settings-search-move-up",
  navFoot: "zotero-agent-settings-window-subtitle",
  navLabel: "zotero-agent-settings-nav-label",
  nextPage: "zotero-agent-settings-catalog-next",
  noEntries: "zotero-agent-settings-empty-entries",
  noReasoning: "zotero-agent-settings-models-reasoning-unsupported",
  overviewToolsNote: "zotero-agent-settings-onboarding-subtitle",
  previousPage: "zotero-agent-settings-catalog-prev",
  purposesLabel: "zotero-agent-settings-models-defaults",
  purposeSetGeneral: "zotero-agent-settings-models-set-general",
  purposeSetConversation: "zotero-agent-settings-models-set-conversation",
  purposeSetSkillRun: "zotero-agent-settings-models-set-skill-run",
  purposeSetTitle: "zotero-agent-settings-models-set-title",
  registrationField: "zotero-agent-settings-chatgpt-workspace",
  removeAuthorization: "zotero-agent-settings-chatgpt-remove",
  removeConnection: "zotero-agent-settings-connection-remove",
  removeModel: "zotero-agent-settings-models-remove",
  saving: "zotero-agent-settings-status-saving",
  searchModels: "zotero-agent-settings-models-search",
  settingsLocalNetworkBody: "zotero-agent-settings-local-network-body",
  settingsLocalNetworkTitle: "zotero-agent-settings-local-network-title",
  setupProgress: "zotero-agent-settings-onboarding-progress",
  signOut: "zotero-agent-settings-chatgpt-sign-out",
  sourceName: "zotero-agent-settings-mcp-source-name",
  switchConnection: "zotero-agent-settings-connections-switch",
  testConnection: "zotero-agent-settings-mcp-test",
  testNone: "zotero-agent-settings-test-untested",
  transportField: "zotero-agent-settings-mcp-source-transport",
} as const satisfies Record<string, ZoteroAgentSettingsLabelKey>;

export type ZoteroAgentSettingsPageLabelKey =
  keyof typeof ZOTERO_AGENT_SETTINGS_PAGE_LABEL_ALIASES;

const parameterized = new Set<string>(
  ZOTERO_AGENT_SETTINGS_PARAMETERIZED_LABEL_KEYS,
);

/**
 * Resolves the configured locale for every static key, published under both its
 * FTL id and its page alias. A key the active locale has not translated is left
 * out of the record, which is what lets the page fall back to readable English.
 */
export function buildZoteroAgentSettingsLabels(): Record<string, string> {
  const resolved = new Map<string, string>();
  for (const key of ZOTERO_AGENT_SETTINGS_LABEL_KEYS) {
    if (parameterized.has(key)) continue;
    const value = getStringOrFallback(key, "");
    if (value) resolved.set(key, value);
  }
  const labels: Record<string, string> = {};
  for (const [key, value] of resolved) labels[key] = value;
  for (const [alias, key] of Object.entries(
    ZOTERO_AGENT_SETTINGS_PAGE_LABEL_ALIASES,
  )) {
    const value = resolved.get(key);
    if (value) labels[alias] = value;
  }
  return labels;
}
