// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "skillRunnerEndpoint": string;
      "backendsConfigJson": string;
      "workflowSettingsJson": string;
      "skillRunnerModelCacheJson": string;
      "skillRunnerDeferredTasksJson": string;
      "skillRunnerRequestLedgerJson": string;
      "skillRunnerLocalRuntimeVersion": string;
      "skillRunnerLocalRuntimeStateJson": string;
      "tagVocabularyStagedJson": string;
      "workflowDir": string;
      "sampleOutputDir": string;
      "hostBridgeLanEnabled": boolean;
      "hostBridgePinPortEnabled": boolean;
      "hostBridgePinnedPort": number;
      "hostBridgeToken": string;
      "hostBridgeTokenCreatedAt": string;
      "hostBridgeTokenRotatedAt": string;
    };
  }
}
