// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "skillRunnerEndpoint": string;
      "backendsConfigJson": string;
      "workflowSettingsJson": string;
      "skillRunnerModelCacheJson": string;
      "skillRunnerDeferredTasksJson": string;
      "skillRunnerRequestLedgerJson": string;
      "skillRunnerSkillDisplayRegistryJson": string;
      "skillRunnerLocalRuntimeVersion": string;
      "skillRunnerLocalRuntimeStateJson": string;
      "tagVocabularyStagedJson": string;
      "collectSkillRunFeedbackEnabled": boolean;
      "markdownReaderEnabled": boolean;
      "workflowDir": string;
      "skillDir": string;
      "contentFeedChannel": string;
      "contentStableFeedUrl": string;
      "contentStableFeedMirrorUrl": string;
      "contentBetaFeedUrl": string;
      "contentBetaFeedMirrorUrl": string;
      "contentDevFeedUrl": string;
      "contentDevFeedMirrorUrl": string;
      "sampleOutputDir": string;
      "runtimeRoot": string;
      "hostBridgeLanEnabled": boolean;
      "hostBridgePinPortEnabled": boolean;
      "hostBridgePinnedPort": number;
      "hostBridgeToken": string;
      "hostBridgeTokenCreatedAt": string;
      "hostBridgeTokenRotatedAt": string;
      "hostBridgeAdvertisedHost": string;
      "hostBridgeMasterTokenEncryptedJson": string;
      "hostBridgeMasterTokenMasked": string;
      "hostBridgeMasterTokenUpdatedAt": string;
      "hostBridgeMasterTokenKeyMaterial": string;
      "hostBridgeDisableWriteApproval": boolean;
      "mcpServer.enabled": boolean;
      "synthesisGitSyncEnabled": boolean;
      "synthesisGitSyncRemoteUrl": string;
      "synthesisGitSyncBranch": string;
      "synthesisGitSyncTokenEncryptedJson": string;
      "synthesisGitSyncTokenMasked": string;
      "synthesisGitSyncTokenUpdatedAt": string;
      "synthesisGitSyncAutoSyncEnabled": boolean;
      "synthesisGitSyncAutoRetryEnabled": boolean;
      "synthesisGitSyncConnectionTestJson": string;
      "synthesisWebDavSyncEnabled": boolean;
      "synthesisWebDavSyncBaseUrl": string;
      "synthesisWebDavSyncRemotePath": string;
      "synthesisWebDavSyncUsername": string;
      "synthesisWebDavSyncCredentialEncryptedJson": string;
      "synthesisWebDavSyncCredentialMasked": string;
      "synthesisWebDavSyncCredentialUpdatedAt": string;
      "synthesisWebDavSyncAutoSyncEnabled": boolean;
      "synthesisWebDavSyncAutoRetryEnabled": boolean;
      "synthesisWebDavSyncConnectionTestJson": string;
    };
  }
}
