export const SYNTHESIS_TOPIC_GRAPH_INDEX_CONTRACT_VERSION = "synthesis-topic-graph-index.v1";
export const SYNTHESIS_TOPIC_GRAPH_INDEX_ALGORITHM_VERSION = "topic-graph-index.v1";
export const SYNTHESIS_TOPIC_GRAPH_INDEX_SCHEMA_VERSION = "1.0.0";
export const SYNTHESIS_TOPIC_GRAPH_INDEX_NODE_MAX = 25_000;
export const SYNTHESIS_TOPIC_GRAPH_INDEX_EDGE_MAX = 100_000;
export const SYNTHESIS_TOPIC_GRAPH_INDEX_STRING_MAX = 4096;
export const SYNTHESIS_TOPIC_GRAPH_INDEX_CHECKPOINT_INTERVAL = 256;
