export const GRAPH_MIN_ZOOM_RATIO = 0.12;
export const GRAPH_MAX_ZOOM_RATIO = 2.4;
export const GRAPH_ZOOM_SLIDER_MAX = 100;
export const GRAPH_LIBRARY_BASE_NODE_SIZE = 4.6;
export const GRAPH_SHARED_EXTERNAL_BASE_NODE_SIZE = 3;
export const GRAPH_SINGLE_EXTERNAL_BASE_NODE_SIZE = 2;
export const GRAPH_LIBRARY_NODE_SIZE_CAP = 8;
export const GRAPH_EXTERNAL_NODE_SIZE_CAP = 4.8;
export const GRAPH_IMPORTANCE_HALO_TOP_RATIO = 0.1;
export const GRAPH_IMPORTANCE_HALO_MAX = 8;
export const GRAPH_LIBRARY_IMPORTANCE_HALO_LIGHT = "rgba(37, 99, 235, 0.52)";
export const GRAPH_LIBRARY_IMPORTANCE_HALO_LIGHT_SOFT =
  "rgba(37, 99, 235, 0.22)";
export const GRAPH_LIBRARY_IMPORTANCE_HALO_DARK = "rgba(147, 197, 253, 0.82)";
export const GRAPH_LIBRARY_IMPORTANCE_HALO_DARK_SOFT =
  "rgba(147, 197, 253, 0.32)";
export const GRAPH_EXTERNAL_IMPORTANCE_HALO_LIGHT = "rgba(180, 83, 9, 0.56)";
export const GRAPH_EXTERNAL_IMPORTANCE_HALO_LIGHT_SOFT =
  "rgba(180, 83, 9, 0.22)";
export const GRAPH_EXTERNAL_IMPORTANCE_HALO_DARK = "rgba(251, 191, 36, 0.86)";
export const GRAPH_EXTERNAL_IMPORTANCE_HALO_DARK_SOFT =
  "rgba(251, 191, 36, 0.34)";
export const CITATION_GRAPH_EDGE_SIZE = 1.05;
export const CITATION_GRAPH_INCOMING_EDGE_COLOR = "#d97706";
export const CITATION_GRAPH_OUTGOING_EDGE_COLOR = "#7c3aed";
