import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { build } from "esbuild";
import { format } from "prettier";

const root = resolve(import.meta.dirname, "..");
const schemaRoot = resolve(
  root,
  "packages/synthesis-contracts/contract-set/canonical-literature-artifacts-v1/schemas",
);
const ajv = new Ajv2020({ allErrors: true, code: { source: true, esm: true } });
const exports: Record<string, string> = {};
for (const [name, filename] of [
  ["validateReferences", "source-reference-artifact.schema.json"],
  ["validateCitation", "citation-analysis-artifact.schema.json"],
  ["validateScore", "literature-score-artifact.schema.json"],
]) {
  const schema = JSON.parse(
    await readFile(resolve(schemaRoot, filename), "utf8"),
  );
  ajv.addSchema(schema);
  exports[name] = schema.$id;
}
const output = await build({
  stdin: {
    contents: standaloneCode(ajv, exports),
    resolveDir: root,
    sourcefile: "canonical-literature-validators.mjs",
  },
  bundle: true,
  platform: "browser",
  format: "esm",
  write: false,
});
const generated = await format(
  "// Generated by scripts/build-canonical-literature-validators.ts.\n" +
    output.outputFiles[0].text,
  { parser: "babel", printWidth: 80 },
);
const target = resolve(
  root,
  "workflows_builtin/literature-workbench-package/lib/canonicalLiteratureValidators.mjs",
);
if (process.argv.includes("--stdout")) {
  process.stdout.write(generated);
} else if (process.argv.includes("--check")) {
  if ((await readFile(target, "utf8")) !== generated) {
    throw new Error("Canonical literature validators need regeneration");
  }
} else {
  await writeFile(target, generated, "utf8");
}
